"""
Datos iniciales — investigación web 2026 (Bialet Massé, Punilla, Córdoba).
Fuentes: bialetmasse.com.ar, El Diario Carlos Paz, Córdoba Turismo, medios regionales.
"""
from __future__ import annotations

LUGARES = [
    {
        "nombre": "Balneario municipal y río Cosquín",
        "localidad": "Bialet Massé",
        "categoria": "naturaleza",
        "descripcion": "Playitas de arena, pileta natural, ideal familias.",
        "distancia_km_bialet": 0.5,
        "tags": "rio,verano,familia",
        "fuente_url": "https://www.eldiariodecarlospaz.com.ar/turismo/2023/12/26/bialet-masse-una-tranquila-localidad-con-paisajes-serranos-imperdibles-191204.html",
    },
    {
        "nombre": "Labios del Indio / Barrancas Bermejas",
        "localidad": "Bialet Massé",
        "categoria": "naturaleza",
        "descripcion": "Formación rocosa, pesca, mates, paredones rojizos.",
        "distancia_km_bialet": 2.0,
        "tags": "rio,fotos,atardecer",
    },
    {
        "nombre": "Sendero Buena Vista (Virgen Medalla Milagrosa)",
        "localidad": "Bialet Massé",
        "categoria": "trekking",
        "descripcion": "1,8 km dificultad moderada, vistas al Valle de Punilla.",
        "distancia_km_bialet": 1.0,
        "tags": "senderismo,vistas",
        "fuente_url": "https://cordobaturismo.gov.ar/experiencias/bialet-masse-buena-vista/",
    },
    {
        "nombre": "Sendero río Mallín — Tobogán del Ailén",
        "localidad": "Bialet Massé",
        "categoria": "trekking",
        "descripcion": "Caminatas guiadas municipales, cascada y pileta natural.",
        "distancia_km_bialet": 3.0,
        "tags": "caminata,guidada",
    },
    {
        "nombre": "Museo y Casa de Cultura Dr. Juan Bialet Massé",
        "localidad": "Bialet Massé",
        "categoria": "cultura",
        "descripcion": "Historia del dique San Roque y del prócer local.",
        "distancia_km_bialet": 0.3,
        "tags": "museo,historia",
    },
    {
        "nombre": "Horno histórico La Argentina (cal hidráulica)",
        "localidad": "Bialet Massé",
        "categoria": "cultura",
        "descripcion": "Patrimonio industrial 1884, construcción dique San Roque.",
        "distancia_km_bialet": 1.5,
        "tags": "patrimonio",
    },
    {
        "nombre": "Dique San Roque / Lago",
        "localidad": "Villa Carlos Paz",
        "categoria": "naturaleza",
        "descripcion": "Deportes náuticos, vistas, paseos. ~15 km de Bialet.",
        "distancia_km_bialet": 15.0,
        "tags": "lago,deportes",
    },
    {
        "nombre": "Plaza Próspero Molina — Festival Cosquín",
        "localidad": "Cosquín",
        "categoria": "festival",
        "descripcion": "Festival Nacional de Folklore, 9 lunas enero.",
        "distancia_km_bialet": 12.0,
        "tags": "folklore,musica",
    },
    {
        "nombre": "Predio del Paseo — Avicultura",
        "localidad": "Santa María de Punilla",
        "categoria": "festival",
        "descripcion": "Fiesta provincial con artistas de primer nivel.",
        "distancia_km_bialet": 8.0,
        "tags": "musica,verano",
    },
    {
        "nombre": "Centro cívico Villa Carlos Paz",
        "localidad": "Villa Carlos Paz",
        "categoria": "ciudad",
        "descripcion": "Cine, peatonal, gastronomía, lago.",
        "distancia_km_bialet": 18.0,
        "tags": "ciudad,shopping",
    },
]

EVENTOS = [
    # Bialet Massé
    {
        "nombre": "Peatonal de la Cerveza Artesanal",
        "localidad": "Bialet Massé",
        "categoria": "gastronomia",
        "fecha_inicio": "2026-01-17",
        "fecha_fin": "2026-02-13",
        "mes_inicio": 1,
        "mes_fin": 2,
        "dia_aprox": "sáb 17/1, vie 6/2 y vie 13/2",
        "descripcion": "Cerveza artesanal, música, mercado, turismo local.",
        "distancia_km_bialet": 0.0,
        "entrada": "gratis",
        "fuente_url": "https://conexioncentro.com.ar/peatonal-cerveza-artesanal-bialet-masse-verano-2026/",
        "tags": "verano,cerveza,parejas",
        "prioridad": 1,
    },
    {
        "nombre": "Carnaval Bialet Massé — 3 noches temáticas",
        "localidad": "Bialet Massé",
        "categoria": "fiesta",
        "fecha_inicio": "2026-02-16",
        "fecha_fin": "2026-02-18",
        "mes_inicio": 2,
        "mes_fin": 2,
        "descripcion": "Norteña, cuarteto y gran cierre. San Martín y Malvinas.",
        "distancia_km_bialet": 0.0,
        "entrada": "gratis",
        "fuente_url": "https://www.carlospazvivo.com/carlos-paz-y-punilla-se-preparan-para-un-fin-de-semana-a-puro-carnaval/",
        "tags": "carnaval,familia",
        "prioridad": 1,
    },
    {
        "nombre": "Festival Día de la Bandera",
        "localidad": "Bialet Massé",
        "categoria": "fiesta",
        "mes_inicio": 6,
        "mes_fin": 6,
        "dia_aprox": "21 de junio",
        "descripcion": "Almuerzo patrio, folklore, emprendedores. Oficina de Turismo.",
        "entrada": "gratis",
        "fuente_url": "https://www.eldiariodecarlospaz.com.ar/provincial/2025/6/18/como-sera-el-festival-de-la-bandera-que-se-hara-en-bialet-masse-236643.html",
        "tags": "invierno,familia",
        "prioridad": 2,
    },
    {
        "nombre": "Peatonal del Chocolate",
        "localidad": "Bialet Massé",
        "categoria": "gastronomia",
        "mes_inicio": 7,
        "mes_fin": 7,
        "dia_aprox": "último sábado julio",
        "descripcion": "Invierno, sendero con historia culmina en la peatonal.",
        "entrada": "gratis",
        "tags": "invierno,chocolate",
        "prioridad": 2,
    },
    {
        "nombre": "Caminatas guiadas Sendero con Historia",
        "localidad": "Bialet Massé",
        "categoria": "actividad",
        "mes_inicio": 5,
        "mes_fin": 11,
        "dia_aprox": "2 por mes — inscripción municipal",
        "descripcion": "Patrimonio y naturaleza. Cupos limitados.",
        "entrada": "gratis",
        "fuente_url": "https://www.eldiariodecarlospaz.com.ar/turismo/2025/5/25/bialet-masse-impulsa-caminatas-guiadas-para-vecinos-turistas-en-temporada-baja-234723.html",
        "tags": "trekking,turismo_eco",
        "prioridad": 3,
    },
    {
        "nombre": "Domingos en Familia — Barrancas Bermejas",
        "localidad": "Bialet Massé",
        "categoria": "actividad",
        "mes_inicio": 1,
        "mes_fin": 3,
        "descripcion": "Actividades en balneario verano.",
        "tags": "familia,verano",
        "prioridad": 3,
    },
    {
        "nombre": "Escenario Callejero Eduardo Falú (marco Cosquín)",
        "localidad": "Bialet Massé",
        "categoria": "cultura",
        "mes_inicio": 1,
        "mes_fin": 2,
        "descripcion": "Noches festivaleras vinculadas al folklore coscoíno.",
        "tags": "folklore,musica",
        "prioridad": 2,
    },
    # Valle de Punilla
    {
        "nombre": "Festival Nacional de Folklore de Cosquín — 66ª edición",
        "localidad": "Cosquín",
        "categoria": "festival",
        "fecha_inicio": "2026-01-24",
        "fecha_fin": "2026-02-01",
        "mes_inicio": 1,
        "mes_fin": 2,
        "descripcion": "9 lunas, Plaza Próspero Molina. Transmisión Canal 10.",
        "distancia_km_bialet": 12.0,
        "entrada": "paga",
        "fuente_url": "https://cbahoy.com.ar/grilla-completa-del-festival-de-cosquin-2026-fechas-artistas-y-horarios-de-cada-luna/",
        "tags": "folklore,iconico,parejas",
        "prioridad": 1,
    },
    {
        "nombre": "Festival de la Avicultura",
        "localidad": "Santa María de Punilla",
        "categoria": "festival",
        "fecha_inicio": "2026-01-14",
        "fecha_fin": "2026-01-22",
        "mes_inicio": 1,
        "mes_fin": 1,
        "descripcion": "Q'Lokura, Abel Pintos, Axel, Euge Quevedo. Predio del Paseo.",
        "distancia_km_bialet": 8.0,
        "entrada": "paga",
        "fuente_url": "https://www.eldiariodecarlospaz.com.ar/sociedad/2026/1/13/cuenta-regresiva-para-vivir-la-avicultura-2026-quienes-tocaran-252561.html",
        "tags": "musica,verano",
        "prioridad": 1,
    },
    {
        "nombre": "Carnaval Villa Carlos Paz — desfile internacional",
        "localidad": "Villa Carlos Paz",
        "categoria": "fiesta",
        "fecha_inicio": "2026-02-16",
        "fecha_fin": "2026-02-16",
        "mes_inicio": 2,
        "mes_fin": 2,
        "descripcion": "400+ artistas, Reloj Cucú a Puente Centenario.",
        "distancia_km_bialet": 18.0,
        "entrada": "gratis",
        "tags": "carnaval",
        "prioridad": 2,
    },
    {
        "nombre": "Carnaval Tanti #ViviTanti",
        "localidad": "Tanti",
        "categoria": "fiesta",
        "fecha_inicio": "2026-02-15",
        "fecha_fin": "2026-02-16",
        "mes_inicio": 2,
        "mes_fin": 2,
        "distancia_km_bialet": 25.0,
        "tags": "carnaval",
        "prioridad": 3,
    },
    # Provincial / feriados turísticos
    {
        "nombre": "Feriado puente — Revolución de Mayo",
        "localidad": "Córdoba / Punilla",
        "categoria": "feriado",
        "fecha_inicio": "2026-05-25",
        "fecha_fin": "2026-05-25",
        "mes_inicio": 5,
        "mes_fin": 5,
        "descripcion": "Escapada larga — promover estadía en Bialet.",
        "tags": "puente,marketing",
        "prioridad": 1,
    },
    {
        "nombre": "Feriado — Independencia Argentina",
        "localidad": "Córdoba / Punilla",
        "categoria": "feriado",
        "fecha_inicio": "2026-07-09",
        "fecha_fin": "2026-07-10",
        "mes_inicio": 7,
        "mes_fin": 7,
        "descripcion": "9 y 10 julio (fin de semana largo turístico).",
        "tags": "puente,invierno",
        "prioridad": 1,
    },
    {
        "nombre": "Feria de Córdoba — Nuestra Señora de la Salud",
        "localidad": "Córdoba capital",
        "categoria": "feria",
        "fecha_inicio": "2026-05-23",
        "fecha_fin": "2026-05-30",
        "mes_inicio": 5,
        "mes_fin": 5,
        "descripcion": "El Arenal, casetas, música, fuegos artificiales.",
        "distancia_km_bialet": 55.0,
        "entrada": "paga",
        "fuente_url": "https://www.diariocordoba.com/feria-de-cordoba/2026/05/22/agenda-feria-cordoba-2026-tienes-130496219.html",
        "tags": "feria,excursion",
        "prioridad": 2,
    },
    {
        "nombre": "Festival Nacional del Cuarteto — Jesús María",
        "localidad": "Jesús María",
        "categoria": "festival",
        "mes_inicio": 12,
        "mes_fin": 12,
        "dia_aprox": "diciembre — Anfiteatro",
        "distancia_km_bialet": 45.0,
        "tags": "cuarteto,musica",
        "prioridad": 2,
    },
    {
        "nombre": "Final Copa Argentina / eventos Kempes",
        "localidad": "Córdoba capital",
        "categoria": "deporte",
        "fecha_inicio": "2026-05-24",
        "fecha_fin": "2026-05-24",
        "mes_inicio": 5,
        "mes_fin": 5,
        "descripcion": "River vs Belgrano — demanda alojamiento Punilla/Kempes.",
        "distancia_km_bialet": 40.0,
        "tags": "futbol,kempes",
        "prioridad": 1,
    },
]

CONTENIDOS = [
    {
        "plataforma": "web",
        "url": "https://bialetmasse.com.ar/eventos/",
        "titulo": "Agenda oficial eventos Bialet Massé",
        "localidad": "Bialet Massé",
        "calidad": "alta",
        "verificado": True,
    },
    {
        "plataforma": "web",
        "url": "https://bialetmasse.com.ar/",
        "titulo": "Guía turística Bialet Massé",
        "localidad": "Bialet Massé",
        "calidad": "alta",
        "verificado": True,
    },
    {
        "plataforma": "youtube",
        "url": "https://www.youtube.com/results?search_query=Bialet+Massé+turismo+Valle+de+Punilla",
        "titulo": "Búsqueda YouTube — Bialet Massé turismo",
        "localidad": "Bialet Massé",
        "calidad": "busqueda",
        "notas": "Recolectar manualmente o con YouTube Data API (YOUTUBE_API_KEY)",
    },
    {
        "plataforma": "youtube",
        "url": "https://www.youtube.com/results?search_query=qué+hacer+en+Cosquín+2026",
        "titulo": "Búsqueda YouTube — Cosquín",
        "localidad": "Cosquín",
        "calidad": "busqueda",
    },
    {
        "plataforma": "youtube",
        "url": "https://www.youtube.com/@Canal10Cordoba",
        "titulo": "Canal 10 Córdoba — transmisión Cosquín y eventos",
        "localidad": "Córdoba",
        "calidad": "alta",
        "notas": "Clips oficiales festival folklore",
    },
    {
        "plataforma": "youtube",
        "url": "https://www.youtube.com/results?search_query=Festival+Cosquín+2026+en+vivo",
        "titulo": "Festival Cosquín 2026 en YouTube",
        "localidad": "Cosquín",
        "calidad": "busqueda",
    },
    {
        "plataforma": "youtube",
        "url": "https://www.youtube.com/results?search_query=Valle+de+Punilla+lugares+para+visitar",
        "titulo": "Valle de Punilla lugares",
        "localidad": "Valle de Punilla",
        "calidad": "busqueda",
    },
    {
        "plataforma": "instagram",
        "url": "https://www.instagram.com/explore/tags/bialetmasse/",
        "titulo": "#bialetmasse en Instagram",
        "localidad": "Bialet Massé",
        "calidad": "busqueda",
        "notas": "Requiere Meta API para descarga automática",
    },
    {
        "plataforma": "instagram",
        "url": "https://www.instagram.com/explore/tags/valledepunilla/",
        "titulo": "#valledepunilla",
        "localidad": "Valle de Punilla",
        "calidad": "busqueda",
    },
    {
        "plataforma": "instagram",
        "url": "https://www.instagram.com/explore/tags/festivaldecosquin/",
        "titulo": "#festivaldecosquin",
        "localidad": "Cosquín",
        "calidad": "busqueda",
    },
    {
        "plataforma": "tiktok",
        "url": "https://www.tiktok.com/tag/bialetmasse",
        "titulo": "#bialetmasse TikTok",
        "localidad": "Bialet Massé",
        "calidad": "busqueda",
    },
    {
        "plataforma": "tiktok",
        "url": "https://www.tiktok.com/tag/valledepunilla",
        "titulo": "#valledepunilla TikTok",
        "localidad": "Valle de Punilla",
        "calidad": "busqueda",
    },
    {
        "plataforma": "tiktok",
        "url": "https://www.tiktok.com/tag/cosquin2026",
        "titulo": "#cosquin2026",
        "localidad": "Cosquín",
        "calidad": "busqueda",
    },
    {
        "plataforma": "web",
        "url": "https://cordobaturismo.gov.ar/agenda/fiestas-y-festivales-en-cordoba/",
        "titulo": "Córdoba Turismo — Fiestas y festivales",
        "localidad": "Córdoba",
        "calidad": "alta",
        "verificado": True,
    },
    {
        "plataforma": "web",
        "url": "https://www.eldiariodecarlospaz.com.ar/",
        "titulo": "El Diario de Carlos Paz — agenda Punilla",
        "localidad": "Valle de Punilla",
        "calidad": "alta",
    },
]
